# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 031a3b74986f86cf12d37b3daa1753f3f02a9ced4f7ca194876996f5608663e940cb77e8aa11c380600041b3b99f2538956cd925365ebb34c04c25e8fdb23ea8

test:
  secret_key_base: 443cd1e5f53eff6828d8873a28016c69796a4406d0a7a67a9b6ed9b5b0956f25362b6a7d79b2f5c8cf7908a9fab9f7288f9f189fecff43993dfac996a6d56e08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
